### ISSUE TITLE
Meeting Notes: Roadmap for 2017Q1 (32 release)

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#604]
Attendees:
@badevuru
@spiderkeys 
@nerdgilbert 

## Goals for the release:
* This should be the initial build that supports Trident for kick-starter backers
* Continued focus on keeping things stable
* Initial releases of required features

## Todo:
- [ ] Update #570 with Roadmap adjustments
- [ ] @badevguru Setup feature board 
- [ ] @spiderkeys, @badevguru Setup initial pattern design meetings

## Timeline
* Release should be ready by mid April 2017
* Beta builds should be in active testing by mid March 2017 

## Process for feature lifecycle
* Design/Approach
* Scope with stakeholders (estimated duration)
* Feature Map/ Task breakdown
* Prioritized on Feature Board
* QA Plan
* Support Handoff

#### Patterns
* Guaranteed msg delivery @spiderkeys 
  - Sync of values
* Enable/Disable of plugins by board capability @badevguru
* Controls arbitration @spiderkeys 
* Cloud Mgt @badevguru
* Automated testing @badevguru

#### Required
* Plugin Enable/Disable (by Product capability) @badevguru
* Trident Controls @spiderkeys 
* Refine realtime video @spiderkeys 
  - WebSockets
  - Dual Streams
  - Settings PI Checkup
  - Upgrade bootloader & firmware
  - IOS Mjpeg support
  - Full frame image capture
  - Unique Cam IDs
  - Timestamp correction
  - Vendor recommended improvements
* Mobile capable default theme @badevguru
* Internet Streaming @badevguru
* Internet Control @badevguru
* Trident ESC firmware @spiderkeys 
* Power warning/shutdown system @spiderkeys 
* Trident Test Jigs @nerdgilbert 
* Wifi Modules @nerdgilbert 
  - Build system
  - Go Pro Plugin
  - Wifi Managment
* Topside @nerdgilbert 
* Vision enhancements @nerdgilbert 
* Cloud Features @badevguru
  - Data Sync
  - Replay
  - Video Hub
  - Rov Profiles
  - Backend Infrastructure
  - Certificate Service

#### Optional
* MCU Sync Logic/Pattern @spiderkeys 
* Resin firmware update improvements @spiderkeys
